version: "3.7"
services:
   server:
      image: omaxanderson/server
      ports:
         - "5001:5001"
      volumes:
         - ./:/app
      environment:
         - ENV=production
      secrets:
         - spotify_client_id
         - spotify_client_secret
   client:
      image: omaxanderson/client
      ports:
         - "9000:9000"
secrets:
   spotify_client_id:
      external: true
   spotify_client_secret:
      external: true

