version: "3.7"
services:
   server:
      image: omaxanderson/spotify-app
      ports:
         - "5001:5001"
         - "9000:9000"
      volumes:
         - ./:/app
      secrets:
         - spotify_client_id
         - spotify_client_secret
secrets:
   spotify_client_id:
      external: true
   spotify_client_secret:
      external: true

